### ISSUE TITLE
Request updates！

### ISSUE THREAD

**Issue by tiandaoyuxi** [neuratech-ai/ComfyUI-MultiGPU#15]
Request updates to provide support for https://github.com/kijai/ComfyUI-HunyuanVideoWrapper

HyVideoModelLoader
HyVideoVAELoader
DownloadAndLoadHyVideoTextEncoder

**Comment by MrReclusive** [comment]
Its really easy to add yourself to hy, ill post what did when im at my computer.
It is litterely just adding a line, extendending a line, and removing a line, from the sampler, decoder, and video encoder. Hy yells at me if i try to load the text encoder to different gpu then the sampler.

Not sure its feasible for neuratech to add hunyuan nodes atm consider they are being updated/changed almost daily.

Idk, maybe ill just fork hunyuan with the changes for you. May not be able to update as fast as they are though.

**Comment by MrReclusive** [comment]
And the reason i add it to the decoder, videoencoder, and sampler is because the model loader will follow the sampler, and the vae loader will follow the videoencoder/decoder.
And if you have 3 gpus and set encoder and decoder to different gpus, it will keep moving the vae between gpus.

I needed this for hunyuan because 2 of my 4090s are on a 1x pcie riser switch, so loading and unloading these models was slower then generation.

**Comment by tiandaoyuxi** [comment]
Great, 
looking forward to it. Waiting for better graphics cards to be released. 
The cost of updating hardware was really high before this. cool！

**Comment by MrReclusive** [comment]
``

> Great, looking forward to it. Waiting for better graphics cards to be released. The cost of updating hardware was really high before this. cool！

Here you go, I was able to get it to allow you to move text encoder too. so you can run everything on different gpu's if you have enough GPU's

https://github.com/MrReclusive/ComfyUI-HunyuanVWMultiGPU


And yeah, 5090 looking nice with that 32gb vram.

I just realized they made another change today, 5 hours ago to be exact:) If you have any issues I'll have it fixed tomorrow.
This is why neaurtech shouldn't support it officially yet :)

The only file that I'm changing is to nodes.py

**Comment by tiandaoyuxi** [comment]
THX. cool！ I'm going to give it a try now…

**Comment by MrReclusive** [comment]
> THX. cool！ I'm going to give it a try now…

completely up to date as of 3 hours ago, trying to get them to pull, they update way to much to maintain this ;)

**Comment by tiandaoyuxi** [comment]
> > 謝謝。酷！ 我現在就去嘗試…
> 
> 截至 3 小時前，完全是最新的，試圖讓他們拉動，他們更新了很多方式來維持這一點；）

I tested it in an environment of 3090+4090 earlier yesterday. It is very effective. cool！
Today I went to git pull it. THX！！！

**Comment by tiandaoyuxi** [comment]
> > THX. cool！ I'm going to give it a try now…
> 
> completely up to date as of 3 hours ago, trying to get them to pull, they update way to much to maintain this ;)

![image](https://github.com/user-attachments/assets/ad896d62-5145-474e-b231-da0968087e9b)

Is this a bug?

**Comment by MrReclusive** [comment]
> > > THX. cool！ I'm going to give it a try now…
> > 
> > 
> > completely up to date as of 3 hours ago, trying to get them to pull, they update way to much to maintain this ;)
> 
> ![image](https://private-user-images.githubusercontent.com/111102932/397614628-ad896d62-5145-474e-b231-da0968087e9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzY2NjMsIm5iZiI6MTczNDY3NjM2MywicGF0aCI6Ii8xMTExMDI5MzIvMzk3NjE0NjI4LWFkODk2ZDYyLTUxNDUtNDc0ZS1iMjMxLWRhMDk2ODA4N2U5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwNjMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTY1OGFmMjNmZDk5MDk2MTNlYTNlYzhjYjc0ZjBkMTdjZTBkMjhiYmIxMzMyNjQzOWQ3YmI2MzRkZTVlMDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oKTBd4q2w19wEvepKA1XKaTjB3fyTMkFTSMbQWDnWtY)
> 
> Is this a bug?

yes, but not with any of this, something to do with how windows label's gpu's and its not just in this.
I do 3d rendering with iray, and it also counts them in reverse.
anything cuda based or python based seems to count differently then windows, and pretty sure windows is the one that is wrong.
windows lists my rtx 4080 as GPU 0, but in terms of how its connected to the motherboard, the 4080 is gpu 2, which is how everything else sees it. 
my 4090's are 0 and 1, and 4080 2 in everything except windows, windows has it completely reversed.
good to know its not just me, i thought it had something to do with the pcie riser.

**Comment by MrReclusive** [comment]
![image](https://github.com/user-attachments/assets/9f2109eb-f5fd-45d8-9190-8eae783d9d09)

**Comment by MrReclusive** [comment]
also, if you want to know more about whats going on with your gpu during this.
i suggest looking at copy, copy1, copy2 and cuda.
![image](https://github.com/user-attachments/assets/5a96ea0d-0335-457d-8087-43d7a68f5666)

**Comment by tiandaoyuxi** [comment]
Thank you very much, I will use it more to test it. 
I also need to know which information to send to different GPUs is a better choice. 
These require me to conduct some tests to complete.
Good job.

**Comment by MrReclusive** [comment]
> Thank you very much, I will use it more to test it. I also need to know which information to send to different GPUs is a better choice. These require me to conduct some tests to complete. Good job.

For me, on a 2 gpu run, a 4080 and 4090, I encode and decode on the 4080, sample on the 4090, but thats due to my 1x pcie limitation on the 4090, if unloading and loading wasn't an issue, I would probably run decode and sample both on the 4090 as the decode can use a lot of vram.

I am talking with kijai about getting this in the main wrapper, his concern is people not running cuda.
looking like we are going to move to separate node for gpu selection that will connect to an optional input the sampler, encoders, decodes, loaders, etc.

**Comment by MrReclusive** [comment]
He just confirmed, as soon as I make these changes for optional with a stand alone node, he will add it to the main build.
So multigpu will be part of the main wrapper!

**Comment by MrReclusive** [comment]
also wishing nvidia still supported nvlink on consumer cards. would love to bridge the 4090's to a single 48gb device.. Kind of want to pick up a couple of 3090's and bridge those.

**Comment by tiandaoyuxi** [comment]
> > Thank you very much, I will use it more to test it. I also need to know which information to send to different GPUs is a better choice. These require me to conduct some tests to complete. Good job.
> 
> For me, on a 2 gpu run, a 4080 and 4090, I encode and decode on the 4080, sample on the 4090, but thats due to my 1x pcie limitation on the 4090, if unloading and loading wasn't an issue, I would probably run decode and sample both on the 4090 as the decode can use a lot of vram.
> 
> I am talking with kijai about getting this in the main wrapper, his concern is people not running cuda. looking like we are going to move to separate node for gpu selection that will connect to an optional input the sampler, encoders, decodes, loaders, etc.

Jukka Seppänen？ This is so cool. Waiting for Implementation

**Comment by tiandaoyuxi** [comment]
> 也希望 nvidia 仍然支援消費卡上的 nvlink。很想將 4090 橋接到單一 48GB 裝置。

Nvidia's castration is too severe. A6000ada has been cancelled. I can only consider dual A6000 at the moment and hope for 5090 to return it

**Comment by MrReclusive** [comment]
> > 也希望 nvidia 仍然支援消費卡上的 nvlink。很想將 4090 橋接到單一 48GB 裝置。
> 
> Nvidia's castration is too severe. A6000ada has been cancelled. I can only consider dual A6000 at the moment and hope for 5090 to return it

yeah, its been nuts, I've looked into the a6000's and all that, the issue always became the lower cuda core count. For the 3d rendering I do, Cuda cores and Ray tracing cores are of huge importance, more then vram, most my scenes fit in 12gb, the biggest will fit in 16gb.
while yes, it has 48gb, it also has 6000 less cuda cores, and I know they are different cores, but I still have yet seen, a direct Iray rendering comparison between an A6000 and a RTX 4090, and I couldn't justify spending $3000 more for a card that MAY not be as fast. even if those cores were faster, and it rendered just as fast or faster then the 4090, I doubt its faster then 2 4090's that cost me less then a single a6000.

That's why I've been looking at refurbished 3090's, for $2000 can get 48gb and 20,000 cuda cores since it DOES have nvlink, but also don't know what kind of troubles I would face getting nvlink to work properly in these ai work loads.
